### ISSUE TITLE
How To add new node?

### ISSUE THREAD

**Issue by wuwei3** [eclipse/fog05#139]
For now, I have successfully installed the fog, but I don't know what and how to use it, for example, if i want to add new node into it, how could I do with wiriting code? and is there any simple way to do like by webside or something else?

If it is possible, could you please list the functions of fog for now?

**Comment by gabrik** [comment]
In order to "add" another node you need to install in another machine the agent, the os plugin, the network plugin and one runtime plugin, so everything except yaks, and then you have to configure it to use the same yaks server of the first one.


Some examples can be found here: 
https://github.com/atolab/fog05_demo/tree/master/fim_api

Docs can be found here: https://atolab.github.io/fog05-doc/fog05.html#module-fog05.fimapi

With fog05 you can deploy differt kind of applications: LXD containers, KVM VMs or binary applicaiton of the different nodes that are part of the fog system

**Comment by wuwei3** [comment]
What if another node installed the yaks? any impact?
If I don't start the yaks on another machine, can I add the node?

**Comment by gabrik** [comment]
No impact, but you must configure all the node to connect to the same YAKS server
